# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  epicgamesbot:
    image: epicgamesbot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5053:5053
